indicatorsByOutcome <- function() {
  div(style = "font-size: 12pt; page-break-inside: avoid;",
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #deeaf6; border-left: solid #000000 2px; border-top: solid #000000 2px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #deeaf6; font-weight: bold; border-top: solid #000000 2px; border-bottom: solid #000000 1px;",
              "Outcome"),
          div(style = "width: 1px; background-color: #deeaf6; border-right: solid #000000 1px; border-top: solid #000000 2px; border-bottom: solid #000000 1px;"),
          div(style = "width: 5px; background-color: #deeaf6; border-left: solid #000000 1px; border-top: solid #000000 2px; border-bottom: solid #000000 1px;"),
          div(style = "width: 75%; background-color: #deeaf6; font-weight: bold; border-top: solid #000000 2px; border-bottom: solid #000000 1px; border-right: solid #000000 2px;", "Indicator"),
          div(style = "width: 14px;")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #426bba; color: #ffffff; font-weight: bold; border-top: solid #000000 1px; border-bottom: solid #000000 1px; border-left: solid #000000 2px;"),
          div(style = "width: 25%; background-color: #426bba; color: #ffffff; font-weight: bold; border-top: solid #000000 1px; border-bottom: solid #000000 1px; border-right: solid #000000 1px;",
              "Improved attitudes between young people from different backgrounds"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_11a", "1.1a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who think that relations between Protestants and Catholics are better than they were five years ago"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_11a2", "1.1a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who think that relations between Protestants and Catholics will be better in five years' time"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_11b", "1.1b")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who feel favourable towards people from: Catholic communities, Protestant communities, Minority Ethnic communities"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #426bba; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #426bba; color: #ffffff; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "Young people engaged in bringing the community together"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_12a", "1.2a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of young people who regularly socialise or play sport with people from a different religious community"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_12b", "1.2b")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of young people who have: shared sports facilities or equipment; shared classes; done projects, with pupils from other schools where the pupils are from a different religious background"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #c4db00; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #c4db00; color: #002469; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "Increased use of shared space and services"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_21a", "2.1a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who think that Protestants and Catholics tend to go to different local shops or use different GP surgeries and other services in their area"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_21b", "2.1b")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of people who think that leisure centres, parks, libraries, and shopping centres in their area are 'shared and open' to both Protestants and Catholics"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_21c", "2.1c")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of those who have children at school who think that their child's school is somewhere they can be open about their cultural identity"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_21d", "2.1d")),
                  div(class = "table-pad"),
                  div(class = "ind", "% whose school has been involved in shared education with another school in the last academic year, broken down by type of activity"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_21e", "2.1e")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of people who see the area they live in as Protestant, Catholic or mixed"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #c4db00; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #c4db00; color: #002469; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "Shared space is accessible to all"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_22a", "2.2a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who would define their neighbourhood/workplace as somewhere they can be open about their cultural identity"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_22b", "2.2b")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who would prefer mixed religion neighbourhoods, workplaces, and schools"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_22c", "2.2c")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of first preference applications to post-primary integrated schools that do not results in admissions"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #d0cece; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #d0cece; color: #002469; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "Reduction in the prevalence of hate crime and intimidation"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_31a", "3.1a")),
                  div(class = "table-pad"),
                  div(class = "ind", "Number of hate crimes"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_31b", "3.1b")),
                  div(class = "table-pad"),
                  div(class = "ind", "Number of people presenting as homeless as a result of intimidation"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_31c", "3.1c")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of people who felt:", "annoyed by republican murals; intimidated by republican murals", "annoyed by loyalist murals; intimidated by loyalist murals"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #d0cece; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #d0cece; color: #002469; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "A community where places and spaces are safe for all"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_32a", "3.2a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of people who see town centres as safe and welcoming places for people of all walks of life"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_32b", "3.2b")),
                  div(class = "table-pad"),
                  div(class = "ind", "% of people feeling safe going to events held in: a GAA club, an Orange Hall, a Protestant secondary school, a Catholic secondary school"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_32c", "3.2c")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who would like to see peace walls come down now or in the near future"),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #002469; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;"),
          div(style = "width: 25%; background-color: #002469; color: #ffffff; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 1px;", "Increased sense of community belonging"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_41a", "4.1a")),
                  div(class = "table-pad"),
                  div(class = "ind", HTML("% who feel a sense of belonging to:<ul><li>their neighbourhood</li><li>Northern Ireland</li></ul>")),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_41b", "4.1b")),
                  div(class = "table-pad"),
                  div(class = "ind", HTML("% who feel they have an influence on the decisions made in:<ul><li>their neighbourhood</li><li>Northern Ireland</li></ul>")),
                  div(class = "row-indent"))),
          div(class = "row-indent")),
      
      
      div(class = "row", style = "display: flex;",
          div(class = "row-indent"),
          div(style = "width: 5px; background-color: #002469; border-left: solid #000000 2px; border-top: solid #000000 1px; border-bottom: solid #000000 2px;"),
          div(style = "width: 25%; background-color: #002469; color: #ffffff; font-weight: bold; border-right: solid #000000 1px; border-top: solid #000000 1px; border-bottom: solid #000000 2px;", "Cultural diversity is celebrated"),
          div(style = "width: 75%;",
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad"),
                  div(class = "ind-no", a(href = "#Indicator_42a", "4.2a")),
                  div(class = "table-pad"),
                  div(class = "ind", "% who think the culture and traditions of: Catholic communities; Protestant communities; Minority Ethnic communities, add to the richness and diversity of Northern Ireland society"),
                  div(class = "row-indent")),
              div(class = "row", style = "display: flex;",
                  div(class = "row-indent"),
                  div(class = "table-pad", style = "border-bottom: solid #000000 2px"),
                  div(class = "ind-no" , style = "border-bottom: solid #000000 2px", a(href = "#Indicator_42b", "4.2b")),
                  div(class = "table-pad", style = "border-bottom: solid #000000 2px"),
                  div(class = "ind", style = "border-bottom: solid #000000 2px", "% who feel their own cultural identity is respected by society"),
                  div(class = "row-indent"))),
          div(class = "row-indent"))
  )
}