sharedInfographic <- function() {
  
  leisure <- colPct(NILT, LCOPEN, c("Yes, definitely", "Yes, probably"))
  park <- colPct(NILT, PARKOPEN, c("Yes, definitely", "Yes, probably"))
  library <- colPct(NILT, LIBOPEN, c("Yes, definitely", "Yes, probably"))
  shopping <- colPct(NILT, SHCNOPEN, c("Yes, definitely", "Yes, probably"))
  
  workplace <- round2(dataNew$f12_workplace)
  neighbourhood <- round2(dataNew$f12_neighbourhood)
  school <- round2(dataNew$f12_school)
  
  plot_ly(fig7,
          type = "scatter",
          mode = "markers") %>%
    layout(
      xaxis = list(showgrid = FALSE,
                   zeroline = FALSE,
                   visbile = FALSE,
                   showticklabels = FALSE,
                   fixedrange = TRUE),
      
      yaxis = list(showgrid = FALSE,
                   zeroline = FALSE,
                   visible = FALSE,
                   fixedrange = TRUE),
      
      showlegend = FALSE,
      
      images = list(
        list(source = dataURI(file = "images/leisure centre.png"),
             x = 0, y = 0.93, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "top"),
        list(source = dataURI(file = "images/park.png"),
             x = 0, y = 0.69, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "top"),
        list(source = dataURI(file = "images/library.png"),
             x = 0, y = 0.44, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "top"),
        list(source = dataURI(file = "images/shopping centre.png"),
             x = 0, y = 0.02, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "bottom"),
        list(source = dataURI(file = "images/workplace.png"),
             x = 0.53, y = 0.94, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "top"),
        list(source = dataURI(file = "images/neighbourhood.png"),
             x = 0.53, y = 0.5, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "middle"),
        list(source = dataURI(file = "images/religion.png"),
             x = 0.53, y = 0.03, sizex = 0.16, sizey = 0.16, xanchor = "left", yanchor = "bottom")
      ),
      
      shapes = list(
        list(type = line,
             x0 = 0.5, x1 = 0.5, y0 = 0, y1 = 1,
             line = list(color = "#999999", width = 2, dash = "dash")),
        list(type = "rect",
             x0 = 0.17, x1 = 0.17 + leisure * 0.003,
             y0 = 0.84, y1 = 0.94,
             xref = "paper", yref = "paper",
             fillcolor = "#b0deff",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17 + leisure * 0.003, x1 = 0.47,
             y0 = 0.84, y1 = 0.94,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17, x1 = 0.17 + park * 0.003,
             y0 = 0.59, y1 = 0.69,
             xref = "paper", yref = "paper",
             fillcolor = "#999999",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17 + park * 0.003, x1 = 0.47,
             y0 = 0.59, y1 = 0.69,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17, x1 = 0.17 + library * 0.003,
             y0 = 0.35, y1 = 0.45,
             xref = "paper", yref = "paper",
             fillcolor = "#85afd6",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17 + library * 0.003, x1 = 0.47,
             y0 = 0.35, y1 = 0.45,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17, x1 = 0.17 + shopping * 0.003,
             y0 = 0.08, y1 = 0.18,
             xref = "paper", yref = "paper",
             fillcolor = "#2d4673",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.17 + shopping * 0.003, x1 = 0.47,
             y0 = 0.08, y1 = 0.18,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7, x1 = 0.7 + workplace * 0.003,
             y0 = 0.84, y1 = 0.94,
             xref = "paper", yref = "paper",
             fillcolor = "#b0deff",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7 + workplace * 0.003, x1 = 1,
             y0 = 0.84, y1 = 0.94,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7, x1 = 0.7 + neighbourhood * 0.003,
             y0 = 0.45, y1 = 0.55,
             xref = "paper", yref = "paper",
             fillcolor = "#999999",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7 + neighbourhood * 0.003, x1 = 1,
             y0 = 0.45, y1 = 0.55,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7, x1 = 0.7 + school * 0.003,
             y0 = 0.08, y1 = 0.18,
             xref = "paper", yref = "paper",
             fillcolor = "#85afd6",
             line = list(width = 0)),
        list(type = "rect",
             x0 = 0.7 + school * 0.003, x1 = 1,
             y0 = 0.08, y1 = 0.18,
             xref = "paper", yref = "paper",
             fillcolor = "#e8e8e8",
             line = list(width = 0))
      ),
      
      annotations = list(
        list(text = paste0("<b>", leisure, "%</b>"),
             showarrow = FALSE,
             x = 0.17 + leisure * 0.0015, xref = "paper", xanchor = "center",
             y = 0.89, yref = "paper", yanchor = "middle"),
        list(text = "Think that leisure centres are 'shared\nand open' to both Catholics and\nProtestants",
             showarrow = FALSE,
             x = 0.17, xref = "paper", xanchor = "left",
             y = 0.84, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", park, "%</b>"),
             showarrow = FALSE,
             x = 0.17 + park * 0.0015, xref = "paper", xanchor = "center",
             y = 0.64, yref = "paper", yanchor = "middle"),
        list(text = "Think that parks are 'shared and\nopen' to both Catholics and\nProtestants",
             showarrow = FALSE,
             x = 0.17, xref = "paper", xanchor = "left",
             y = 0.59, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", library, "%</b>"),
             showarrow = FALSE,
             x = 0.17 + library * 0.0015, xref = "paper", xanchor = "center",
             y = 0.4, yref = "paper", yanchor = "middle"),
        list(text = "Think that libraries are 'shared and\nopen' to both Catholics and\nProtestants",
             showarrow = FALSE,
             x = 0.17, xref = "paper", xanchor = "left",
             y = 0.35, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", shopping, "%</b>"),
             showarrow = FALSE,
             x = 0.17 + shopping * 0.0015, xref = "paper", xanchor = "center",
             y = 0.13, yref = "paper", yanchor = "middle",
             font = list(color = "#ffffff")),
        list(text = "Think that shopping centres are\n'shared and open' to both Catholics\nand Protestants",
             showarrow = FALSE,
             x = 0.17, xref = "paper", xanchor = "left",
             y = 0.08, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", workplace, "%</b>"),
             showarrow = FALSE,
             x = 0.7 + workplace * 0.0015, xref = "paper", xanchor = "center",
             y = 0.89, yref = "paper", yanchor = "middle"),
        list(text = "Prefer a mixed religion workplace",
             showarrow = FALSE,
             x = 0.7, xref = "paper", xanchor = "left",
             y = 0.84, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", neighbourhood, "%</b>"),
             showarrow = FALSE,
             x = 0.7 + neighbourhood * 0.0015, xref = "paper", xanchor = "center",
             y = 0.5, yref = "paper", yanchor = "middle"),
        list(text = "Prefer a mixed religion neighbourhood",
             showarrow = FALSE,
             x = 0.7, xref = "paper", xanchor = "left",
             y = 0.45, yref = "paper", yanchor = "top",
             align = "left"),
        list(text = paste0("<b>", school, "%</b>"),
             showarrow = FALSE,
             x = 0.7 + school * 0.0015, xref = "paper", xanchor = "center",
             y = 0.13, yref = "paper", yanchor = "middle"),
        list(text = "Prefer mixed religion schools",
             showarrow = FALSE,
             x = 0.7, xref = "paper", xanchor = "left",
             y = 0.08, yref = "paper", yanchor = "top",
             align = "left")
      ),
      
      modebar = list(remove = c("zoom", "pan", "zoomIn2d", "zoomOut2d",
                                "autoscale", "resetScale2d", "hoverCompareCartesian", "hoverClosestCartesian")),
      
      font = list(family = "Helvetica", size = 14)
      
    ) %>%
    
    config(displaylogo = FALSE)
  
}